### ISSUE TITLE
Name. Squirrely wrong.

### ISSUE THREAD

**Issue by tomsmeding** [lieuwex/Squiggly#2]
Squiggly. ~. That's how this name is. Please:
1. Make it shorter;
2. Fix the spelling error.

These in arbitrary order, and squash. Suggestions:
- Bob(e)c (brace-open-brace-close)
- Clocep (closure-ception)
- Synclo (reference to the relatedness of {} with synchronicity (or a-~) and closures)
- Squirrely
- Brac (BRaces with Asynchronous Closures)
- Faecl (Fabulous Asynchronous Esoteric Closure Language)
- Facl (Fabulous Asynchronous Closure Language)

**Comment by lieuwex** [comment]
Thanks for 2. But I'm not going to change the name. The name isn't long at all '{}'. Just 2 characters, I don't see the problem.

**Comment by lieuwex** [comment]
I have thought about it, a shorter pronunciation is handy. What about SquigglySquiggly?

**Comment by tomsmeding** [comment]
Lol. Realisation's struck?
Sure.
